# Generated by Django 4.2 on 2024-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_assessment_result_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(default="editable", max_length=50),
        ),
    ]
