# Generated by Django 4.2 on 2024-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_assignment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment_edit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("assigned_class", models.CharField(max_length=50)),
                ("teacher_id", models.CharField(max_length=50)),
                (
                    "request_status",
                    models.CharField(default="no_request", max_length=10),
                ),
                ("date_enrolled", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
