# Generated by Django 4.2 on 2024-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_assessment_edit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment_edit",
            name="request_status",
            field=models.CharField(max_length=10),
        ),
    ]
