# Generated by Django 4.2 on 2024-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_assessment_edit_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("registrar", "Registrar"),
                    ("department_head", "Department Head"),
                    ("student", "Student"),
                ],
                max_length=20,
            ),
        ),
    ]
